var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/index.config.js
var index_config_exports = {};
__export(index_config_exports, {
  default: () => index_config_default
});
module.exports = __toCommonJS(index_config_exports);
var index_config_default = {
  ali: {
    token: "",
    token280: "token280"
  },
  quark: {
    cookie: ""
  },
  uc: {
    cookie: "cookie",
    token: "token",
    ut: "ut"
  },
  y115: {
    cookie: ""
  },
  muou: {
    url: ""
  },
  wogg: {
    url: ""
  },
  leijing: {
    url: ""
  },
  tgsou: {
    tgPic: false,
    count: 0,
    url: "",
    channelUsername: ""
  },
  tgchannel: {},
  sites: {
    list: []
  },
  pans: {
    list: []
  },
   danmu: {
    urls: [
           { address: "https://logdanmu.dpdns.org", name: "默认1" },
           { address: "https://fjj0417.dpdns.org/87654321", name: "默认2" }, 
           { address: "https://dm.stardm.us.kg:443/87654321", name: "默认3" }, 
           { address: "https://danmu.14812910.xyz/87654321", name: "默认4" }, 
           { address: "https://313236.xyz/87654321", name: "默认5" }
          ],
    autoPush: true
  },
 t4: {list: [
    {name: "✈️关注TG频道@stymei",
      address: "http://zhangqun1818.serv00.net:6628/?spider=独播库"},
    {name: "📡IPTV直播",
      address: "https://iptv.jsnzkpg.uk"},
    {name: "🐟斗鱼直播",
      address: "https://php.doube.eu.org/spider/php/斗鱼直播.php"},
      {name: "🐯虎牙直播",
      address: "https://php.doube.eu.org/spider/php/虎牙直播.php"},
    {name: "🅱️哔哩直播",
      address: "https://bilibili.jsnzkpg.uk"},
    {name: "🎞️影视爬虫",
      address: "https://dy.7772888.xyz/api.php/tvbox"},
    {name: "▶️Emby嗅探",
      address: "http://zhangqun1818.serv00.net:6628/?spider=emby"},
    {name: "🍁非凡PHP",
      address: "https://php.doube.eu.org/spider/php/非凡资源.php"},
    {name: "🐣天堂PHP",
      address: "https://php.doube.eu.org/spider/php/电影天堂.php"},
      {name: "💧欧乐PHP",
      address: "https://php.doube.eu.org/spider/php/欧乐影院.php"},
      {name: "🦄U视影视",
      address: "http://zhangqun1818.serv00.net:5052/?sp=UVod"},
      {name: "🥔土豆影视",
      address: "http://zhangqun1818.serv00.net:5052/?sp=土豆浏览器"},
      {name: "🐈‍⬛七猫短剧",
      address: "http://zhangqun1818.serv00.net:6628/?spider=七猫短剧"},
      {name: "🍚西饭短剧",
      address: "http://zhangqun1818.serv00.net:6628/?spider=西饭短剧"},
     {name: "🦛河马短剧",
      address: "http://zhangqun1818.serv00.net:5052/?sp=河马短剧"},
     {name: "🇨🇳央视栏目",
      address: "https://catbox.n13.club/18/央视影视.php"},
    {name: "📻凤凰FM",
      address: "http://zhangqun1818.serv00.net:6628/?spider=凤凰fm"},
      {name: "🍉瓜子影视",
      address: "https://catbox.n13.club/ai/瓜子影视.php"},
      {name: "🦄獨播庫",
      address: "http://bob2.hkt.net.cn/miraplay/dbo.php"},
      {name: "🐰優兔影視",
      address: "https://catbox.n13.club/ai/优兔APP.php"},
      {name: "❤️‍🔥優視頻",
      address: "http://zhangqun1818.serv00.net:5052/?sp=UVod"},
      {name: "🥔土豆網",
      address: "http://zhangqun1818.serv00.net:5052/?sp=土豆浏览器"},
      {name: "🎦奇優影院",
      address: "http://zhangqun1818.serv00.net:5052/?sp=奇优动漫"},
      {name: "🐥小鴨影視",
      address: "http://zhangqun1818.serv00.net:5052/?sp=小鸭子看看"},
      {name: "👀可視影院",
      address: "http://142.171.248.206:5757/api/可视影院?pwd=dzyyds"},
      {name: "👁️新浪視頻",
      address: "http://142.171.248.206:5757/api/新浪资源?do=py&pwd=dzyyds"},
      {name: "🪹泥視頻",
      address: "http://142.171.248.206:5757/api/泥视频?pwd=dzyyds"},
      {name: "🍁楓林網",
      address: "http://142.171.248.206:5757/api/枫林影视?pwd=dzyyds"},
      {name: "☢️歐樂影院",
      address: "https://php.doube.eu.org/spider/php/欧乐影院.php"},
      {name: "❇️愛奇藝",
      address: "https://iqiyizyapi.com/api.php/provide/vod"},
      {name: "🏎️快車影视",
      address: "https://caiji.kuaichezy.org/api.php/provide/vod/"},
      {name: "💽克隆電影",
      address: "http://zhangqun1818.serv00.net/klhj.php"},
      {name: "🐣电影天堂",
      address: "https://php.doube.eu.org/spider/php/电影天堂.php"},
      {name: "🍁非凡资源",
      address: "https://php.doube.eu.org/spider/php/非凡资源.php"},
      {name: "📺專享影视",
      address: "http://sspa8.top:99/php/专享.php"},
      {name: "🎹酷我音樂",
      address: "http://sspa8.top:99/php/酷我.php"},
       {name: "📺努努影院",
      address: "http://zhangqun1818.serv00.net:5052/?sp=努努影院"},
      {name: "🍋‍愛瓜影視2",
      address: "http://zhangqun1818.serv00.net:5052/?sp=爱瓜影视"},
      {name: "😹哇哇影視2",
      address: "http://zhangqun1818.serv00.net:5052/?sp=哇哇"},
      {name: "👫🏻人人影視",
      address: "http://zhangqun1818.serv00.net:6628/?spider=人人影视"},  
      {name: "👫🏻人人影視2",
      address: "https://catbox.n13.club/18/人人影视.php"},
      {name: "🎦电视影視",
      address: "http://zhangqun1818.serv00.net/zh/2242.php"},
      {name: "🧍‍♂️凡客影視",
      address: "http://zhangqun1818.serv00.net:6628/?spider=凡客tv"},
      {name: "👫🏻人人影視",
      address: "http://zhangqun1818.serv00.net:6628/?spider=人人影视"},
      {name: "🦄獨播庫采集",
      address: "http://zhangqun1818.serv00.net:6628/?spider=独播库"}, 
      {name: "✈️飛快TV",
      address: "http://zhangqun1818.serv00.net:6628/?spider=飞快tv"}, 
      {name: "🍄蘑菇影视",
      address: "https://www.5o5k.com/api.php/provide/vod/"},
      {name: "💨清风影视",
      address: "http://sspa8.top:8100/php/清风.php"},
      {name: "📺embyj影视",
      address: "http://zhangqun1818.serv00.net:6628/?spider=emby"},
      {name: "📺旺旺影视",
      address: "http://zhangqun1818.serv00.net/ww.php"},
      {name: "📺淘片影视",
      address: "https://www.taopianzy.com/cjapi/mc/vod/json.html"},
      {name: "📺鬼片之家",
      address: "https://catbox.n13.club/ai/guipian360.php"},
      {name: "📺如意影视",
      address: "http://cj.rycjapi.com/api.php/provide/vod/"},
      {name: "📺爱瓜影视",
      address: "http://zhangqun1818.serv00.net/aigua1.php"},
      {name: "📺采集影视2",
      address: "http://zhangqun1818.serv00.net/cj/cjjh.php"},
      {name: "📺tvbox影视",
      address: "https://dy.7772888.xyz/api.php/tvbox"}, 
      {name: "📺猫眼影视",
      address: "https://api.maoyanapi.top/api.php/provide/vod"},
      {name: "📺魅蓝影视",
      address: "https://tv1.aagay.com/api.php/provide/vod/"},
      {name: "📺无水影视",
      address: "https://api.wsyzy.net/api.php/provide/vod/"},
      {name: "📺旺剧影视",
      address: "https://ww.tyyszy5.com/api.php/provide/vod/"},
      {name: "🎬飘零资源",
      address: "https://p2100.net/api.php/provide/vod/"},
      {name: "📺天天影视",
      address: "https://www.ttdm6.me/api.php/provide/vod"},
      {name: "📺剧屋影视",
      address: "https://m.juwu.tv/api.php/provide/vod"},
      {name: "📺四圈影视",
      address: "https://pg.fenwe078.cf/api.php/provide/vod/"},
      {name: "📺海洋影视",
      address: "http://www.seacms.org/api.php/provide/vod"},
      {name: "📺蛋蛋影视",
      address: "https://ddmf.net/api.php/provide/vod/"},
      {name: "📺播剧影视",
      address: "https://www.ysxq.cc/api.php/provide/vod/"},
      {name: "📺影剧影视",
      address: "https://yjzy.tv/api.php/provide/vod/"},
      {name: "📺漫道影视",
      address: "https://www.mandao.cc/api.php/provide/vod/"}
      {name: "🎞️影视爬虫",
      address: "https://dy.7772888.xyz/api.php/tvbox"},
      {name: "🍿七壹影视",
      address: "https://catbox.n13.club/ai/七壹APP.php"},
      {name: "⏳暴风采集",
      address: "http://by.bfzyapi.com/api.php/provide/vod"},   
      {name: "📺枫叶音乐",
      address: "https://catbox.n13.club/ai/枫叶音乐.php"},
      {name: "📺荐片影视2",
      address: "http://zhangqun1818.serv00.net:6628/?spider=荐片"},
      {name: "📺影探影视",
      address: "https://catbox.n13.club/18/影探影视.php"},
      {name: "📺喜福影视",
      address: "https://catbox.n13.club/ai/喜福短剧.php"},
      {name: "📺甜圈影视",
      address: "https://catbox.n13.club/ai/甜圈短剧.php"},
      {name: "📺樱花资源",
      address: "https://m3u8.apiyhzy.com/api.php/provide/vod/"},  
      {name: "📺人影资源",
      address: "https://catbox.n13.club/18/人人影视"},
      {name: "🎦电视影视",
      address: "http://zhangqun1818.serv00.net/zh/2242.php"},
      {name: "📺小猪影视",
      address: "https://catbox.n13.club/ai/小猪APP.php"},
      {name: "📺数字影视",
      address: "https://catbox.n13.club/ai/数字APP.php"},
      {name: "📺人影影视",
      address: "http://zhangqun1818.serv00.net:6628/?spider=人人影视"},
      {name: "📺凡客影视",
      address: "http://zhangqun1818.serv00.net:6628/?spider=凡客tv"},
      {name: "📺恋鱼影视",
      address: "https://catbox.n13.club/t9/lianyu.php"},
      {name: "📺星之阁影视",
      address: "https://catbox.n13.club/t9/xingzhige.php"},
      {name: "🎬豆瓣资源",
      address: "https://caiji.dbzy5.com/api.php/provide/vod"},
      {name: "🎬茅台资源",
      address: "https://caiji.maotaizy.cc/api.php/provide/vod"},
      {name: "🎬卧龙资源",
      address: "https://wolongzyw.com/api.php/provide/vod"},
      {name: "🎬iKun资源",
      address: "https://ikunzyapi.com/api.php/provide/vod"},
      {name: "🎬电影天堂",
      address: "http://caiji.dyttzyapi.com/api.php/provide/vod"},
      {name: "🎬猫眼资源",
      address: "https://api.maoyanapi.top/api.php/provide/vod"},
      {name: "🎬量子资源",
      address: "https://cj.lzcaiji.com/api.php/provide/vod"},
      {name: "🎬360 资源",
      address: "https://360zyzz.com/api.php/provide/vod"},
      {name: "🎬极速资源",
      address: "https://jszyapi.com/api.php/provide/vod"},
      {name: "🎬魔都资源",
      address: "https://www.mdzyapi.com/api.php/provide/vod"},
      {name: "🎬非凡资源",
      address: "https://api.ffzyapi.com/api.php/provide/vod"},
      {name: "🎬最大资源",
      address: "https://api.zuidapi.com/api.php/provide/vod"},
      {name: "🎬无尽资源",
      address: "https://api.wujinapi.me/api.php/provide/vod"},
      {name: "🎬新浪资源",
      address: "https://api.xinlangapi.com/xinlangapi.php/provide/vod"},
      {name: "🎬旺旺资源",
      address: "https://api.wwzy.tv/api.php/provide/vod"},
      {name: "🎬速播资源",
      address: "https://subocaiji.com/api.php/provide/vod"},
      {name: "🎬金鹰点播",
      address: "https://jinyingzy.com/api.php/provide/vod"},
      {name: "🎬光速资源",
      address: "https://api.guangsuapi.com/api.php/provide/vod"},
      {name: "🎬红牛资源",
      address: "https://www.hongniuzy2.com/api.php/provide/vod"},
      {name: "🎬U酷影视",
      address: "https://api.ukuapi88.com/api.php/provide/vod"},
      {name: "🎬魔都动漫",
      address: "https://caiji.moduapi.cc/api.php/provide/vod"},
      {name: "🎬如意资源",
      address: "https://cj.rycjapi.com/api.php/provide/vod"},
      {name: "🎬豪华资源",
      address: "https://hhzyapi.com/api.php/provide/vod"},
      {name: "☁️百度雲zy ",
      address: "https://api.apibdzy.com/api.php/provide/vod"},
      {name: "🎬艾旦影视",
      address: "https://lovedan.net/api.php/provide/vod"},
      {name: "🎬豆瓣点播",
      address: "https://caiji.dbzy.tv/api.php/provide/vod/at/josn"},
      {name: "🎬腐剧点播",
      address: "http://www.fuju2024.cc:8013/ruifenglb_api.php/provide/vod/"},
      {name: "🎬牛牛点播",
      address: "https://api.niuniuzy.me/api.php/provide/vod/"},
      {name: "🎬丫丫点播",
      address: "https://cj.yayazy.net/api.php/provide/vod/"},
      {name: "🎬影图点播",
      address: "https://cj.vodimg.top/api.php/provide/vod/"},
      {name: "🎬U酷点播",
      address: "https://api.ukuapi.com/api.php/provide/vod/"},
      {name: "🎬索尼点播",
      address: "https://suoniapi.com/api.php/provide/vod/"},
      {name: "🎬非凡点播2",
      address: "http://cj.ffzyapi.com/api.php/provide/vod/"},
      {name: "🎬量子点播",
      address: "https://cj.lziapi.com/api.php/provide/vod/"},
      {name: "🎬快车点播",
      address: "https://caiji.kczyapi.com/api.php/provide/vod/from/kcm3u8/"},
      {name: "🎬闪电点播",
      address: "http://sdzyapi.com/api.php/provide/vod/"},
      {name: "🎬樱花点播",
      address: "https://m3u8.apiyhzy.com/api.php/provide/vod/"},
      {name: "🎬卧龙点播",
      address: "https://collect.wolongzyw.com/api.php/provide/vod/"},
      {name: "🎬虎牙点播",
      address: "https://www.huyaapi.com/api.php/provide/vod/"},
      {name: "🎬无尽点播2",
      address: "https://api.wujinapi.com/api.php/provide/vod/"},
      {name: "🎬速博点播",
      address: "https://subocaiji.com/api.php/provide/vod/"},
      {name: "🎬最大点播",
      address: "http://zuidazy.me/api.php/provide/vod/"},
      {name: "🎬火狐点播",
      address: "https://hhzyapi.com/api.php/provide/vod/"},
      {name: "🎬旺旺点播",
      address: "http://zhangqun1818.serv00.net/ww.php"},
      {name: "📡IPTV直播",
      address: "https://t4.jsnzkpg.uk"},
      {name: "🐟斗鱼直播",
      address: "https://catbox.n13.club/ai/斗鱼直播.php"},
      {name: "🐯虎牙直播",
      address: "https://php.doube.eu.org/spider/php/虎牙直播.php"},
      {name: "🅱️哔哩直播",
      address: "https://bilibili.jsnzkpg.uk"},
      {name: "📽️喜福短剧",
      address: "https://catbox.n13.club/ai/喜福短剧.php"},
      {name: "🐈‍⬛七猫短剧",
      address: "http://zhangqun1818.serv00.net:6628/?spider=七猫短剧"},
      {name: "🍚西饭短剧",
      address: "http://zhangqun1818.serv00.net:6628/?spider=西饭短剧"},
      {name: "🦛河马短剧",
      address: "http://zhangqun1818.serv00.net:5052/?sp=河马短剧"},
      {name: "🎦iptv采集",
      address: "https://iptv.jsnzkpg.uk"},
      {name: "📺央视影视",
      address: "https://catbox.n13.club/18/央视影视.php"},
      {name: "📺央影直播",
      address: "https://zhangqun1818.serv00.net/cctv.php"},
      {name: "📺PY",
      address: "http://zhangqun1818.serv00.net/py.php"},
      {name: "📺js",
      address: "http://zhangqun1818.serv00.net/js.php"},
      {name: "🐦‍🔥鳳凰FM",
      address: "http://zhangqun1818.serv00.net:6628/?spider=凤凰fm"},
      {name: "🐰兔小貝",
      address: "http://zhangqun1818.serv00.net:6628/?spider=兔小贝"},
      {name: "🎦斗鱼2",
      address: "https://php.doube.eu.org/spider/php/斗鱼直播.php"},
      {name: "🎦哔哩直播",
      address: "https://bilibili.jsnzkpg.uk"}

]},

]},
  cms: {list: [
{name: "🌪️暴风采集",
address: "http://by.bfzyapi.com/api.php/provide/vod"},
{name: "🪐iQiYi采集",
address: "https://iqiyizyapi.com/api.php/provide/vod"}
]},
  alist: [
    {
      name: "🐉神族九帝",
      server: "https://alist.shenzjd.com"
    },
    {
      name: "💢repl",
      server: "https://ali.liucn.repl.co"
    }
  ],
  color: [
    {
      light: {
        bg: "https://i2.100024.xyz/2024/01/13/pptcej.webp",
        bgMask: "0x50ffffff",
        primary: "0xff446732",
        onPrimary: "0xffffffff",
        primaryContainer: "0xffc5efab",
        onPrimaryContainer: "0xff072100",
        secondary: "0xff55624c",
        onSecondary: "0xffffffff",
        secondaryContainer: "0xffd9e7cb",
        onSecondaryContainer: "0xff131f0d",
        tertiary: "0xff386666",
        onTertiary: "0xffffffff",
        tertiaryContainer: "0xffbbebec",
        onTertiaryContainer: "0xff002020",
        error: "0xffba1a1a",
        onError: "0xffffffff",
        errorContainer: "0xffffdad6",
        onErrorContainer: "0xff410002",
        background: "0xfff8faf0",
        onBackground: "0xff191d16",
        surface: "0xfff8faf0",
        onSurface: "0xff191d16",
        surfaceVariant: "0xffe0e4d6",
        onSurfaceVariant: "0xff191d16",
        inverseSurface: "0xff2e312b",
        inverseOnSurface: "0xfff0f2e7",
        outline: "0xff74796d",
        outlineVariant: "0xffc3c8bb",
        shadow: "0xff000000",
        scrim: "0xff000000",
        inversePrimary: "0xffaad291",
        surfaceTint: "0xff446732"
      },
      dark: {
        bg: "https://i2.100024.xyz/2024/01/13/pptg3z.webp",
        bgMask: "0x50000000",
        primary: "0xffaad291",
        onPrimary: "0xff173807",
        primaryContainer: "0xff2d4f1c",
        onPrimaryContainer: "0xffc5efab",
        secondary: "0xffbdcbb0",
        onSecondary: "0xff283420",
        secondaryContainer: "0xff3e4a35",
        onSecondaryContainer: "0xffd9e7cb",
        tertiary: "0xffa0cfcf",
        onTertiary: "0xff003738",
        tertiaryContainer: "0xff1e4e4e",
        onTertiaryContainer: "0xffbbebec",
        error: "0xffffb4ab",
        onError: "0xff690005",
        errorContainer: "0xff93000a",
        onErrorContainer: "0xffffdad6",
        background: "0xff11140e",
        onBackground: "0xffe1e4d9",
        surface: "0xff11140e",
        onSurface: "0xffe1e4d9",
        surfaceVariant: "0xff43483e",
        onSurfaceVariant: "0xffe1e4d9",
        inverseSurface: "0xffe1e4d9",
        inverseOnSurface: "0xff2e312b",
        outline: "0xff8d9286",
        outlineVariant: "0xff43483e",
        shadow: "0xff000000",
        scrim: "0xff000000",
        inversePrimary: "0xff446732",
        surfaceTint: "0xffaad291"
      }
    },
    {
      light: {
        bg: "https://i2.100024.xyz/2024/01/13/pi2rpw.webp",
        bgMask: "0x50ffffff",
        primary: "0xff666014",
        onPrimary: "0xffffffff",
        primaryContainer: "0xffeee58c",
        onPrimaryContainer: "0xff1f1c00",
        secondary: "0xff625f42",
        onSecondary: "0xffffffff",
        secondaryContainer: "0xffe9e4be",
        onSecondaryContainer: "0xff1e1c05",
        tertiary: "0xff3f6654",
        onTertiary: "0xffffffff",
        tertiaryContainer: "0xffc1ecd5",
        onTertiaryContainer: "0xff002114",
        error: "0xffba1a1a",
        onError: "0xffffffff",
        errorContainer: "0xffffdad6",
        onErrorContainer: "0xff410002",
        background: "0xfffef9eb",
        onBackground: "0xff1d1c14",
        surface: "0xfffef9eb",
        onSurface: "0xff1d1c14",
        surfaceVariant: "0xffe7e3d0",
        onSurfaceVariant: "0xff1d1c14",
        inverseSurface: "0xff323128",
        inverseOnSurface: "0xfff5f1e3",
        outline: "0xff7a7768",
        outlineVariant: "0xffcbc7b5",
        shadow: "0xff000000",
        scrim: "0xff000000",
        inversePrimary: "0xffd1c973",
        surfaceTint: "0xff666014"
      },
      dark: {
        bg: "https://i2.100024.xyz/2024/01/13/pi2reo.webp",
        bgMask: "0x50000000",
        primary: "0xffd1c973",
        onPrimary: "0xff353100",
        primaryContainer: "0xff4d4800",
        onPrimaryContainer: "0xffeee58c",
        secondary: "0xffcdc8a3",
        onSecondary: "0xff333117",
        secondaryContainer: "0xff4a482c",
        onSecondaryContainer: "0xffe9e4be",
        tertiary: "0xffa6d0b9",
        onTertiary: "0xff0e3727",
        tertiaryContainer: "0xff274e3d",
        onTertiaryContainer: "0xffc1ecd5",
        error: "0xffffb4ab",
        onError: "0xff690005",
        errorContainer: "0xff93000a",
        onErrorContainer: "0xffffdad6",
        background: "0xff14140c",
        onBackground: "0xffe7e2d5",
        surface: "0xff14140c",
        onSurface: "0xffe7e2d5",
        surfaceVariant: "0xff49473a",
        onSurfaceVariant: "0xffe7e2d5",
        inverseSurface: "0xffe7e2d5",
        inverseOnSurface: "0xff323128",
        outline: "0xff949181",
        outlineVariant: "0xff49473a",
        shadow: "0xff000000",
        scrim: "0xff000000",
        inversePrimary: "0xff666014",
        surfaceTint: "0xffd1c973"
      }
    },
    {
      light: {
        bg: "https://i2.100024.xyz/2024/01/13/qrnuwt.webp",
        bgMask: "0x50ffffff",
        primary: "0xFF2B6C00",
        onPrimary: "0xFFFFFFFF",
        primaryContainer: "0xFFA6F779",
        onPrimaryContainer: "0xFF082100",
        secondary: "0xFF55624C",
        onSecondary: "0xFFFFFFFF",
        secondaryContainer: "0xFFD9E7CA",
        onSecondaryContainer: "0xFF131F0D",
        tertiary: "0xFF386666",
        onTertiary: "0xFFFFFFFF",
        tertiaryContainer: "0xFFBBEBEB",
        onTertiaryContainer: "0xFF002020",
        error: "0xFFBA1A1A",
        onError: "0xFFFFFFFF",
        errorContainer: "0xFFFFDAD6",
        onErrorContainer: "0xFF410002",
        background: "0xFFFDFDF5",
        onBackground: "0xFF1A1C18",
        surface: "0xFFFDFDF5",
        onSurface: "0xFF1A1C18",
        surfaceVariant: "0xFFE0E4D6",
        onSurfaceVariant: "0xFF1A1C18",
        inverseSurface: "0xFF2F312C",
        onInverseSurface: "0xFFF1F1EA",
        outline: "0xFF74796D",
        outlineVariant: "0xFFC3C8BB",
        shadow: "0xFF000000",
        scrim: "0xFF000000",
        inversePrimary: "0xFF8CDA60",
        surfaceTint: "0xFF2B6C00"
      },
      dark: {
        bg: "https://i2.100024.xyz/2024/01/13/qrc37o.webp",
        bgMask: "0x50000000",
        primary: "0xFF8CDA60",
        onPrimary: "0xFF133800",
        primaryContainer: "0xFF1F5100",
        onPrimaryContainer: "0xFFA6F779",
        secondary: "0xFFBDCBAF",
        onSecondary: "0xFF283420",
        secondaryContainer: "0xFF3E4A35",
        onSecondaryContainer: "0xFFD9E7CA",
        tertiary: "0xFFA0CFCF",
        onTertiary: "0xFF003737",
        tertiaryContainer: "0xFF1E4E4E",
        onTertiaryContainer: "0xFFBBEBEB",
        error: "0xFFFFB4AB",
        errorContainer: "0xFF93000A",
        onError: "0xFF690005",
        onErrorContainer: "0xFFFFDAD6",
        background: "0xFF1A1C18",
        onBackground: "0xFFE3E3DC",
        outline: "0xFF8D9286",
        onInverseSurface: "0xFF1A1C18",
        inverseSurface: "0xFFE3E3DC",
        inversePrimary: "0xFF2B6C00",
        shadow: "0xFF000000",
        surfaceTint: "0xFF8CDA60",
        outlineVariant: "0xFF43483E",
        scrim: "0xFF000000",
        surface: "0xFF1A1C18",
        onSurface: "0xFFC7C7C0",
        surfaceVariant: "0xFF43483E",
        onSurfaceVariant: "0xFFC7C7C0"
      }
    }
  ]
};
